import "./modules/buttonScrollTop.js";
import "./modules/modal-menu.js";
import "./modules/menu.js";
import "./modules/swiper-product.js";
import "./modules/modal-choose-size.js";
import "./modules/openDescription.js";
import "./modules/pages-navigation.js";
import "./modules/size-table.js";
import "./modules/productCard.js";